In [5]:
import vitaldb
import plotly.express as px

import pandas as pd

In [6]:
vf = vitaldb.VitalFile("0010.vital").to_pandas(['Solar8000/BT', 'Solar8000/HR', 'Solar8000/RR_CO2', 'BIS/BIS', 'Solar8000/PLETH_SPO2'], interval=1)

In [7]:
vf

,Solar8000/BT,Solar8000/HR,Solar8000/RR_CO2,BIS/BIS,Solar8000/PLETH_SPO2
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,0.0,NaN
4,NaN,NaN,NaN,0.0,NaN
...,...,...,...,...,...
20988,NaN,NaN,NaN,0.0,NaN
20989,23.5,NaN,NaN,0.0,NaN
20990,NaN,NaN,NaN,0.0,NaN
20991,23.5,NaN,NaN,0.0,NaN
20992,NaN,NaN,NaN,NaN,NaN

In [8]:
vf = vf.reset_index()
vf = vf.rename(columns={"index": 'time',  "Solar8000/BT": "body temperature", 'BIS/BIS': 'Bispectral Index', 'Solar8000/RR_CO2': "Respiratory rate" })
# Solar8000/PLETH_SPO2 - Насыщение крови кислородом

In [9]:
vf = vf.dropna()

In [10]:
figure = px.line(vf, x="time", y="body temperature")
figure.show()

In [11]:
# x_list = vf.time.tolist()
# delta_t = 5
#
# x_list = x_list[0:20]
# print(x_list)
# print('-------------------')
# #

In [12]:
figure = px.line(vf, x="time", y="Bispectral Index")
figure.show()

In [13]:
figure = px.line(vf, x="time", y="Respiratory rate")
figure.show()

In [14]:
figure = px.line(vf, x="time", y="Solar8000/PLETH_SPO2")
figure.show()

In [15]:
import numpy as np
from scipy.fft import fft

x = np.array([1, 2, 3, 4])
res = fft(x)
print(res)

[10.-0.j -2.+2.j -2.-0.j -2.-2.j]

In [25]:
vf = vitaldb.VitalFile("0010.vital").to_pandas(['SNUADC/ECG_V5'], interval=1)
vf.dropna()

Empty DataFrame
Columns: [SNUADC/ECG_V5]
Index: []

In [29]:
vf = vf.rename(columns={"index": 'time' })

figure = px.line(vf, x="time", y="SNUADC/ECG_V5")
figure.show()

In [32]:
vf

        time  SNUADC/ECG_V5
0          0            NaN
1          1            NaN
2          2            NaN
3          3            NaN
4          4            NaN
...      ...            ...
20988  20988            NaN
20989  20989            NaN
20990  20990            NaN
20991  20991            NaN
20992  20992            NaN

[20993 rows x 2 columns]