In [56]:
import pandas as pd
import plotly.express as px
import numpy as np
import re
import nltk

In [57]:
df = pd.read_csv('products.csv')

проелятье размерноти

семантика = смысл

In [58]:
df

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,7179d2f6c4ad50a17d014ca1d2815156,2015-12-01 10:15:43 +0000,http://www.flipkart.com/walldesign-small-vinyl...,WallDesign Small Vinyl Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7KFJAKSTDY9G,1500.0,730.0,"[""http://img6a.flixcart.com/image/wall-decorat...",False,Buy WallDesign Small Vinyl Sticker for Rs.730 ...,No rating available,No rating available,WallDesign,"{""product_specification""=>[{""key""=>""Number of ..."
19996,71ac419198359d37b8fe5e3fffdfee09,2015-12-01 10:15:43 +0000,http://www.flipkart.com/wallmantra-large-vinyl...,Wallmantra Large Vinyl Stickers Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE9F5URNQGJCGH,1429.0,1143.0,"[""http://img6a.flixcart.com/image/sticker/z/g/...",False,Buy Wallmantra Large Vinyl Stickers Sticker fo...,No rating available,No rating available,Wallmantra,"{""product_specification""=>[{""key""=>""Number of ..."
19997,93e9d343837400ce0d7980874ece471c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7VAYDKQZEBSD,1299.0,999.0,"[""http://img5a.flixcart.com/image/sticker/b/s/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ..."
19998,669e79b8fa5d9ae020841c0c97d5e935,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE8YSVEPPCZ42Y,1499.0,1199.0,"[""http://img5a.flixcart.com/image/sticker/4/2/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ..."
19999,cb4fa87a874f715fff567f7b7b3be79c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE88KN9ZDSGZKY,1499.0,999.0,"[""http://img6a.flixcart.com/image/sticker/z/k/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ..."

In [59]:
df['description']

0        Key Features of Alisha Solid Women's Cycling S...
1        FabHomeDecor Fabric Double Sofa Bed (Finish Co...
2        Key Features of AW Bellies Sandals Wedges Heel...
3        Key Features of Alisha Solid Women's Cycling S...
4        Specifications of Sicons All Purpose Arnica Do...
                               ...
19995    Buy WallDesign Small Vinyl Sticker for Rs.730 ...
19996    Buy Wallmantra Large Vinyl Stickers Sticker fo...
19997    Buy Elite Collection Medium Acrylic Sticker fo...
19998    Buy Elite Collection Medium Acrylic Sticker fo...
19999    Buy Elite Collection Medium Acrylic Sticker fo...
Name: description, Length: 20000, dtype: object

In [60]:
df['description'] = df['description'].astype(str)

предобрадотать, дикт,

In [61]:
df['description'] = df['description'].apply(lambda x: x.lower())
# df['description'].str.lower

In [62]:
df['description']

0        key features of alisha solid women's cycling s...
1        fabhomedecor fabric double sofa bed (finish co...
2        key features of aw bellies sandals wedges heel...
3        key features of alisha solid women's cycling s...
4        specifications of sicons all purpose arnica do...
                               ...
19995    buy walldesign small vinyl sticker for rs.730 ...
19996    buy wallmantra large vinyl stickers sticker fo...
19997    buy elite collection medium acrylic sticker fo...
19998    buy elite collection medium acrylic sticker fo...
19999    buy elite collection medium acrylic sticker fo...
Name: description, Length: 20000, dtype: object

In [63]:
df['description'] = df['description'].apply(lambda x: re.sub(r'[^a-z\s]', '', x))

In [64]:
df['description']

0        key features of alisha solid womens cycling sh...
1        fabhomedecor fabric double sofa bed finish col...
2        key features of aw bellies sandals wedges heel...
3        key features of alisha solid womens cycling sh...
4        specifications of sicons all purpose arnica do...
                               ...
19995    buy walldesign small vinyl sticker for rs onli...
19996    buy wallmantra large vinyl stickers sticker fo...
19997    buy elite collection medium acrylic sticker fo...
19998    buy elite collection medium acrylic sticker fo...
19999    buy elite collection medium acrylic sticker fo...
Name: description, Length: 20000, dtype: object

In [65]:
lemmat = nltk.WordNetLemmatizer()
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\topi7\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [66]:
df = df.head(500)
df['description']

0      key features of alisha solid womens cycling sh...
1      fabhomedecor fabric double sofa bed finish col...
2      key features of aw bellies sandals wedges heel...
3      key features of alisha solid womens cycling sh...
4      specifications of sicons all purpose arnica do...
                             ...
495    karatcraft wadell gold diamond  k ring\n      ...
496    yna aviator sunglasses  buy yna aviator sungla...
497    ditukritu warrior aviator sunglasses  buy ditu...
498    american crew solid womens track pants\n      ...
499    allen solly girls gathered dress  buy blue all...
Name: description, Length: 500, dtype: object

In [67]:

df.loc[:,'description'] = df['description'].apply(lambda x: [lemmat.lemmatize(i).strip() for i in x.split(' ')])

In [68]:
df['description']

0      [key, feature, of, alisha, solid, womens, cycl...
1      [fabhomedecor, fabric, double, sofa, bed, fini...
2      [key, feature, of, aw, belly, sandal, wedge, h...
3      [key, feature, of, alisha, solid, womens, cycl...
4      [specification, of, sicons, all, purpose, arni...
                             ...
495    [karatcraft, wadell, gold, diamond, , k, ring,...
496    [yna, aviator, sunglass, , buy, yna, aviator, ...
497    [ditukritu, warrior, aviator, sunglass, , buy,...
498    [american, crew, solid, womens, track, pants, ...
499    [allen, solly, girl, gathered, dress, , buy, b...
Name: description, Length: 500, dtype: object

In [69]:
bow = {}
a = []
a = df['description'].sum()

In [70]:
values, counts = np.unique_counts(a)

In [71]:

ind = np.argsort(counts)[::-1][:999]
values[ind]

array(['', 'of', 'the', 'for', 'and', 'a', 'in', 'to', 'only', 'r',
       'with', 'this', 'product', 'is', 'on', 'at', 'buy', 'boot', 'your',
       'flipkartcom', 'womens', 'from', 'free', 'watch', 'day', 'top',
       'price', 'genuine', 'delivery', 'guarantee', 'replacement',
       'shipping', 'online', 'cash', 'fabric', 'men', 'boy', 'color',
       'detail', 'feature', 'it', 'casual', 'type', 'ring', 'material',
       'or', 'general', 'you', 'india', 'cm', 'printed', 'will', 'style',
       'box', 'sleeve', 'cotton', 'analog', 'are', 'diamond', 'black',
       'look', 'not', 'pair', 'inch', 'by', 'sale', 'package', 'solid',
       'design', 'number', 'brand', 'key', 'ideal', 'girl', 'cover', 'ha',
       'gold', 'neck', 'great', 'code', 'pack', 'occasion', 'weight',
       'collection', 'blue', 'quality', 'all', 'discount', 'shoe', 'that',
       'length', 'size', 'party', 'an', 'planet', 'short', 'content',
       'dimension', 'be', 'white', 'warranty', 'round', 'kurta', 'made',
       'additional', 'no', 'fashion', 'silver', 'these', 'fit', 'dress',
       'sofa', 'model', 'pattern', 'sleeveless', 'na', 'set', 'woman',
       'clutch', 'water', 'care', 'clothes', 'apparel', 'give', 'shop',
       'leather', 'wear', 'sheet', 'digital', 'huge', 'trendy', 'branded',
       'back', 'strap', 'jewellery', 'long', 'case', 'up', 'height',
       'synthetic', 'comfortable', 'multicolor', 'width', 'g', 'one',
       'sport', 'designed', 'metal', 'do', 'footwear', 'k', 'straight',
       'beautiful', 'out', 'formal', 'diwan', 'bed', 'embroidered',
       'gemstone', 'make', 'perfect', 'house', 'connect', 'specification',
       'enhance', 'piece', 'steppings', 'double', 'designer', 'any',
       'empower', 'full', 'considered', 'self', 'kielz', 'may', 'keep',
       'get', 'other', 'when', 'stylish', 'lady', 'choice', 'heel',
       'wearing', 'floral', 'our', 'yes', 'dial', 'finish', 'wash',
       'shirt', 'mm', 'closure', 'display', 'also', 'pocket', 'high',
       'can', 'fine', 'machine', 'glove', 'which', 'if', 'colour',
       'comfort', 'stole', 'sole', 'hallmarked', 'like', 'red', 'light',
       'add', 'best', 'earth', 'side', 'brown', 'print', 'range', 'some',
       'body', 'belt', 'reach', 'vary', 'alloy', 'festive', 'boots',
       'jean', 'new', 'team', 'yellow', 'present', 'name', 'have',
       'please', 'system', 'use', 'used', 'cushion', 'avoid', 'finger',
       'sensor', 'good', 'work', 'bleach', 'lace', 'pepper', 'pick',
       'premium', 'year', 'pearl', 'time', 'making', 'salt', 'n', 'need',
       'diameter', 'cycling', 'gem', 'certified', 'item', 'magnetic',
       'just', 'manufacturing', 'first', 'flaunt', 'sfds', 'through',
       'soft', 'bag', 'come', 'right', 'security', 'more', 'pump',
       'elegant', 'button', 'hard', 'running', 'outfit', 'suitable',
       'dressberry', 'green', 'while', 'season', 'karatcraft', 'life',
       'outer', 'pad', 'own', 'lukewarm', 'lycra', 'per', 'left',
       'series', 'screen', 'durable', 'due', 'dry', 'depth', 'dhaatu',
       'bnc', 'single', 'touch', 'main', 'x', 'sandal', 'chest', 'check',
       'towel', 'ball', 'every', 'installation', 'well', 'upper',
       'curtain', 'home', 'choli', 'legging', 'stain', 'wedding',
       'viscose', 'coloured', 'glamr', 'nishtaa', 'asian', 'punch',
       'exposure', 'location', 'gentle', 'solitaire', 'matching',
       'manufacturer', 'mechanism', 'phase', 'crafted', 'help', 'highly',
       'note', 'door', 'contemporary', 'attractive', 'been', 'setting',
       'chic', 'level', 'experience', 'foot', 'so', 'shilpkala', 'front',
       'alarm', 'polyester', 'unit', 'pillow', 'flat', 'pouch',
       'accessory', 'paper', 'surface', 'flap', 'cold', 'we', 'cloth',
       'service', 'mean', 'durability', 'function', 'construction',
       'selfie', 'shape', 'ray', 'alisha', 'superior', 'clean', 'grey',
       'lighting', 'bedsheet', 'compartment', 'golf', 'slightly', 'take',
       'net', 'flair', 'important', 'promise', 'hour', 'clubbed',
       'included', 'jewel', 'creation', 'purple', 'lifestyle',
       'recognised', 'covered', 'resistant', 'switch', 'month',
       'attention', 'plastic', 'square', 'buddha', 'ct', 'laughing',
       'wireless', 'hr', 'primary', 'offer', 'striped', 'wool', 'world',
       'ultimate', 'over', 'denim', 'according', 'date', 'than', 'chain',
       'seating', 'such', 'king', 'laboratory', 'astrological',
       'detachable', 'gift', 'righthanded', 'go', 'face', 'fabhomedecor',
       'batting', 'govt', 'fade', 'believed', 'artistically', 'belly',
       'taj', 'jqr', 'pas', 'click', 'cleaner', 'hand', 'birth', 'pull',
       'embellished', 'provide', 'properly', 'hole', 'id', 'power',
       'bolster', 'club', 'latest', 'open', 'using', 'cuff', 'upholstery',
       'individual', 'element', 'stateoftheart', 'pink', 'controller',
       'lounge', 'movement', 'demo', 'marvel', 'mg', 'cause',
       'convenience', 'om', 'easy', 'displayed', 'who', 'led',
       'chronograph', 'appeal', 'analogdigital', 'within', 'iron',
       'buckle', 'without', 'heat', 'solitana', 'sapphire', 'rubber',
       'orange', 'dog', 'secured', 'casuals', 'slip', 'washable', 'clasp',
       'pc', 'vishudh', 'today', 'unique', 'eyelet', 'magnum', 'masara',
       'protect', 'nature', 'wired', 'wire', 'musical', 'patch', 'bella',
       'hem', 'slim', 'sized', 'skayvon', 'disney', 'regular', 'rialto',
       'skmei', 'belle', 'wood', 'lcd', 'down', 'ease', 'connoisseur',
       'ml', 'glance', 'rich', 'adjustable', 'connector', 'part',
       'metallic', 'room', 'shoulder', 'fashionable', 'gambe', 'bi',
       'foam', 'aline', 'sun', 'those', 'fitted', 'sharp', 'them', 'cool',
       'curved', 'ensure', 'ethnic', 'franck', 'purity', 'special',
       'space', 'three', 'daily', 'moisture', 'wall', 'off', 'protection',
       'urban', 'provides', 'anarkali', 'seller', 'mesh', 'tree',
       'wealth', 'shade', 'age', 'support', 'vnku', 'second', 'm', 'term',
       'defect', 'wardrobe', 'family', 'showpiece', 'effect', 'placket',
       'picture', 'play', 'bank', 'line', 'condition', 's', 'combination',
       'direct', 'beauty', 'most', 'royal', 'bath', 'card', 'sicons',
       'looking', 'vacuum', 'dust', 'sitting', 'couple', 'dw', 'must',
       'small', 'inside', 'inner', 'instruction', 'carrel', 'throughout',
       'desired', 'weak', 'across', 'image', 'imported', 'precious',
       'known', 'kt', 'prolonged', 'ensures', 'opposing', 'amethyst',
       'jaipur', 'pet', 'poly', 'stop', 'sterling', 'plain', 'planetary',
       'suppressing', 'crystal', 'wearyourshine', 'lasting', 'away',
       'trend', 'la', 'sunlight', 'protective', 'c', 'but', 'object',
       'swimwear', 'notebook', 'horoscope', 'kurti', 'whether',
       'performance', 'periodically', 'asics', 'guidance', 'resin',
       'grab', 'compared', 'lining', 'ratti', 'rapter', 'sleek',
       'everyone', 'spill', 'source', 'u', 'nav', 'little', 'classy',
       'navy', 'pixel', 'group', 'become', 'before', 'skate', 'ezyprnt',
       'complete', 'repair', 'window', 'attached', 'shuz', 'motion',
       'simple', 'attire', 'concerned', 'cap', 'lightly', 'tear', 'kind',
       'deliver', 'bristled', 'brush', 'outdoor', 'subtype', 'gait',
       'scoop', 'festival', 'clack', 'minute', 'mango', 'secondary',
       'contrast', 'customer', 'technology', 'dark', 'acm', 'added',
       'damage', 'depending', 'mouth', 'accent', 'flare', 'tuff',
       'auspicious', 'loop', 'lower', 'satin', 'sunglass', 'base',
       'backlight', 'upto', 'l', 'leave', 'lehenga', 'office', 'table',
       'sandals\ndouble', 'lightweight', 'finest', 'dressing', 'gsm',
       'bow', 'packaging', 'brass', 'clear', 'clarity', 'kg', 'knee',
       'doe', 'order', 'kid', 'ruby', 'air', 'basic', 'battery', 'wong',
       'standard', 'stand', 'aqua', 'artificial', 'half', 'indcrown',
       'combo', 'impact', 'harbour', 'thing', 'mark', 'decor', 'mast',
       'soak', 'sling', 'heavyduty', 'winter', 'better', 'seamless',
       'living', 'gainer', 'cost', 'contact', 'adding', 'addition',
       'vanity', 'cancellation', 'furniture', 'let', 'v',
       'formatattractive', 'shimmery', 'sheer', 'carlton', 'fold', 'food',
       'flex', 'flexible', 'b', 'shampoo', 'moon', 'monitor',
       'shaperounddial', 'modern', 'cardigan', 'checkered', 'loafer',
       'movementmetal', 'their', 'tank', 'zirconia', 'cushioning',
       'certification', 'manetti', 'senior', 'auto', 'd', 'test', 'terry',
       'th', 'semistitched', 'fluidride', 'cut', 'alarmhour', 'once',
       'laser', 'oodles', 'lehnga', 'curation', 'conductor', 'cubic',
       'rw', 'gelcumulus', 'getting', 'distance', 'after', 'against',
       'wide', 'directly', 'save', 'lee', 'furnishing', 'nonreceipt',
       'displayautomatic', 'diva', 'leg', 'corner', 'sweater',
       'sweatshirt', 'newest', 'dimensionmm', 'libas', 'assorted',
       'astonish', 'santosh', 'multiple', 'device', 'further', 'breath',
       'wedge', 'stunning', 'keepsake', 'clara', 'vivacious', 'jeweller',
       'pir', 'pk', 'jacket', 'week', 'stylist', 'skating', 'classic',
       'summersible', 'summary', 'submersibble', 'vizionsports', 'briza',
       'featuring', 'silk', 'keeping', 'oxter', 'bruno', 'feel',
       'overall', 'gathered', 'kitchenware', 'warrantydigital', 'bee',
       'goldtoned', 'ready', 'statement', 'boxnote', 'boys', 'either',
       'bound', 'widthmmwater', 'courier', 'photographic',
       'resistantnight', 'country', 'intimate', 'into', 'crop', 'katela',
       'allowed', 'pretty', 'energy', 'placed', 'being', 'extra',
       'expressive', 'expert', 'art', 'information', 'pot', 'booking',
       'split', 'indistar', 'else', 'colouredboots', 'bellieswhich',
       'eurospa', 'enlarged', 'hoursdisclaimer', 'clubbing', 'however',
       'pricesspecifications', 'turn', 'hip', 'specifically', 'endless',
       'collar', 'herberto', 'bis', 'bis\nbis', 'everyday', 'purpose',
       'cpp', 'two', 'heading', 'want', 'exclusive', 'exciting',
       'catwalk', 'materialsilicone', 'abaya', 'w', 'they', 'yarn', 'yet',
       'youth', 'preciousartificial', 'zipper', 'turbo', 'waistcoat',
       'cmfirst', 'impression', 'providing', 'enhances', 'man', 'pod',
       'mobile', 'traditional', 'handle', 'mache', 'polyvinyl',
       'resistance', 'place', 'completely', 'preference', 'registered',
       'plating', 'effective', 'enhanced', 'elastic', 'quantity',
       'statementspecifications', 'prevent', 'blk', 'bloom', 'too',
       'maxi', 'board', 'bodycon', 'bold', 'grade', 'apple', 'softness',
       'soie', 'close', 'straightmasara', 'blend', 'essential',
       'professional', 'heart', 'religious', 'easily', 'elegance',
       'bengal', 'ensemble', 'position', 'reversible', 'stitched',
       'export', 'pu', 'western', 'bright', 'hidden', 'eye',
       'interlinked', 'required', 'beige', 'positive', 'breitling',
       'kashibo', 'kashmiri', 'similar', 'fcnsan', 'feeling', 'ruffle',
       'panel', 'dual', 'vizion', 'roadster', 'gandhi', 'rose',
       'supplying', 'built', 'laced'], dtype='<U87')

In [72]:
bow = dict()

for index, word in enumerate(values):
    bow[word] = index
print(bow)

{np.str_(''): 0, np.str_('a'): 1, np.str_('a\nfasense'): 2, np.str_('aa'): 3, np.str_('aadivasi'): 4, np.str_('aaliya'): 5, np.str_('ab'): 6, np.str_('aba'): 7, np.str_('abaya'): 8, np.str_('abayamomin'): 9, np.str_('abbb'): 10, np.str_('abhira'): 11, np.str_('able'): 12, np.str_('above'): 13, np.str_('abroad'): 14, np.str_('absorbency'): 15, np.str_('absorbent'): 16, np.str_('absorbs'): 17, np.str_('abstract'): 18, np.str_('ac'): 19, np.str_('accent'): 20, np.str_('accentuate'): 21, np.str_('accepted'): 22, np.str_('accessorise'): 23, np.str_('accessory'): 24, np.str_('according'): 25, np.str_('accurate'): 26, np.str_('ace'): 27, np.str_('achievement'): 28, np.str_('acm'): 29, np.str_('across'): 30, np.str_('acrylic'): 31, np.str_('action'): 32, np.str_('activates'): 33, np.str_('active'): 34, np.str_('activity'): 35, np.str_('actual'): 36, np.str_('actuator'): 37, np.str_('ada'): 38, np.str_('adaptive'): 39, np.str_('adblack'): 40, np.str_('add'): 41, np.str_('addarkorange'): 42, np.str_('added'): 43, np.str_('addiction'): 44, np.str_('adding'): 45, np.str_('addition'): 46, np.str_('additional'): 47, np.str_('address'): 48, np.str_('adivasi'): 49, np.str_('adjustable'): 50, np.str_('admirable'): 51, np.str_('adnored'): 52, np.str_('adolescentsteenagers'): 53, np.str_('adorned'): 54, np.str_('adornment'): 55, np.str_('adriyel'): 56, np.str_('advantageous'): 57, np.str_('advisable'): 58, np.str_('aelkabja'): 59, np.str_('aesthetic'): 60, np.str_('affordable'): 61, np.str_('after'): 62, np.str_('against'): 63, np.str_('age'): 64, np.str_('ahmd'): 65, np.str_('ahmedabad'): 66, np.str_('air'): 67, np.str_('ak'): 68, np.str_('akarakarabha'): 69, np.str_('akspecifications'): 70, np.str_('alarm'): 71, np.str_('alarmhour'): 72, np.str_('alfajr'): 73, np.str_('aline'): 74, np.str_('alisha'): 75, np.str_('all'): 76, np.str_('allen'): 77, np.str_('allow'): 78, np.str_('allowed'): 79, np.str_('allows'): 80, np.str_('alloy'): 81, np.str_('almond'): 82, np.str_('aloe'): 83, np.str_('along'): 84, np.str_('alrams'): 85, np.str_('also'): 86, np.str_('alsoset'): 87, np.str_('alsospecifications'): 88, np.str_('altght'): 89, np.str_('altghtp'): 90, np.str_('althtp'): 91, np.str_('alto'): 92, np.str_('always'): 93, np.str_('amazing'): 94, np.str_('american'): 95, np.str_('amethyst'): 96, np.str_('amount'): 97, np.str_('amp'): 98, np.str_('ample'): 99, np.str_('an'): 100, np.str_('analog'): 101, np.str_('analogdigital'): 102, np.str_('analogue'): 103, np.str_('anand'): 104, np.str_('anarkali'): 105, np.str_('and'): 106, np.str_('andria'): 107, np.str_('angelfish'): 108, np.str_('angle'): 109, np.str_('another'): 110, np.str_('answered'): 111, np.str_('ant'): 112, np.str_('anti'): 113, np.str_('antiodor'): 114, np.str_('antipilling'): 115, np.str_('antique'): 116, np.str_('antishrink'): 117, np.str_('antiwrinkle'): 118, np.str_('any'): 119, np.str_('anymore'): 120, np.str_('anything'): 121, np.str_('apart'): 122, np.str_('aplledblack'): 123, np.str_('apm'): 124, np.str_('apparancegive'): 125, np.str_('apparel'): 126, np.str_('appeal'): 127, np.str_('appealing'): 128, np.str_('appealspecifications'): 129, np.str_('appears'): 130, np.str_('apple'): 131, np.str_('application'): 132, np.str_('applying'): 133, np.str_('approach'): 134, np.str_('approximate'): 135, np.str_('aqua'): 136, np.str_('archies'): 137, np.str_('are'): 138, np.str_('area'): 139, np.str_('arent'): 140, np.str_('aries'): 141, np.str_('armed'): 142, np.str_('arnica'): 143, np.str_('around'): 144, np.str_('arpenaz'): 145, np.str_('arranged'): 146, np.str_('arrival'): 147, np.str_('art'): 148, np.str_('artefact'): 149, np.str_('artificial'): 150, np.str_('artistically'): 151, np.str_('ashley'): 152, np.str_('ashwagandha'): 153, np.str_('asian'): 154, np.str_('asics'): 155, np.str_('ask'): 156, np.str_('assembled'): 157, np.str_('assembly'): 158, np.str_('associated'): 159, np.str_('assorted'): 160, np.str_('astonish'): 161, np.str_('astro'): 162, np.str_('astrological'): 163, np.str_('asvtwl'): 164, np.str_('at'): 165, np.str_('atm'): 166, np.str_('atm\nif'): 167, np.str_('atmagupta'): 168, np.str_('atop'): 169, np.str_('attached'): 170, np.str_('attachment'): 171, np.str_('attain'): 172, np.str_('attention'): 173, np.str_('attenuates'): 174, np.str_('attire'): 175, np.str_('attire\nmagnum'): 176, np.str_('attract'): 177, np.str_('attraction'): 178, np.str_('attractive'): 179, np.str_('audible'): 180, np.str_('augmentation'): 181, np.str_('augmentation\npep'): 182, np.str_('auspicious'): 183, np.str_('auspicious\nthe'): 184, np.str_('ausy'): 185, np.str_('authorised'): 186, np.str_('authorized'): 187, np.str_('auto'): 188, np.str_('automatic'): 189, np.str_('available'): 190, np.str_('availed'): 191, np.str_('aviator'): 192, np.str_('avoid'): 193, np.str_('avon'): 194, np.str_('avsar'): 195, np.str_('aw'): 196, np.str_('award'): 197, np.str_('awardwinning'): 198, np.str_('away'): 199, np.str_('awesome'): 200, np.str_('ayurvedic'): 201, np.str_('azan'): 202, np.str_('b'): 203, np.str_('babeezworld'): 204, np.str_('baby'): 205, np.str_('back'): 206, np.str_('back\nbrown'): 207, np.str_('back\ngreen'): 208, np.str_('back\nmulticoloured'): 209, np.str_('back\nwhite'): 210, np.str_('backlight'): 211, np.str_('bag'): 212, np.str_('bagspecifications'): 213, np.str_('balance'): 214, np.str_('ball'): 215, np.str_('ballerina'): 216, np.str_('ballet'): 217, np.str_('band'): 218, np.str_('bangle'): 219, np.str_('bank'): 220, np.str_('base'): 221, np.str_('based'): 222, np.str_('basic'): 223, np.str_('basis'): 224, np.str_('bath'): 225, np.str_('batsmenthese'): 226, np.str_('battery'): 227, np.str_('batting'): 228, np.str_('battingyour'): 229, np.str_('bay'): 230, np.str_('bazaaar'): 231, np.str_('bb'): 232, np.str_('bbajc'): 233, np.str_('bbza'): 234, np.str_('bc'): 235, np.str_('bdblue'): 236, np.str_('be'): 237, np.str_('beach'): 238, np.str_('beacuse'): 239, np.str_('bead'): 240, np.str_('beaded'): 241, np.str_('bear'): 242, np.str_('beat'): 243, np.str_('beating'): 244, np.str_('beautiful'): 245, np.str_('beautifully'): 246, np.str_('beauty'): 247, np.str_('beauty\nlet'): 248, np.str_('because'): 249, np.str_('become'): 250, np.str_('bed'): 251, np.str_('bedroom'): 252, np.str_('bedsheet'): 253, np.str_('bee'): 254, np.str_('been'): 255, np.str_('before'): 256, np.str_('beginner'): 257, np.str_('behringer'): 258, np.str_('beige'): 259, np.str_('beigepink'): 260, np.str_('being'): 261, np.str_('believed'): 262, np.str_('bell'): 263, np.str_('bella'): 264, np.str_('belle'): 265, np.str_('bellieswhich'): 266, np.str_('belly'): 267, np.str_('belongs'): 268, np.str_('below'): 269, np.str_('belt'): 270, np.str_('bengal'): 271, np.str_('bent'): 272, np.str_('bento'): 273, np.str_('best'): 274, np.str_('better'): 275, np.str_('between'): 276, np.str_('bezel'): 277, np.str_('bhai'): 278, np.str_('bi'): 279, np.str_('big'): 280, np.str_('bigger'): 281, np.str_('bill'): 282, np.str_('bilqis'): 283, np.str_('binding'): 284, np.str_('birth'): 285, np.str_('bis'): 286, np.str_('bis\nbis'): 287, np.str_('black'): 288, np.str_('blackberry'): 289, np.str_('blackgrey'): 290, np.str_('blackladela'): 291, np.str_('blackled'): 292, np.str_('blackmaroon'): 293, np.str_('blackspecifications'): 294, np.str_('bleach'): 295, np.str_('blemishing'): 296, np.str_('blend'): 297, np.str_('blended'): 298, np.str_('blk'): 299, np.str_('block'): 300, np.str_('blood'): 301, np.str_('bloom'): 302, np.str_('blooming'): 303, np.str_('blue'): 304, np.str_('bluestone'): 305, np.str_('bm'): 306, np.str_('bmjd'): 307, np.str_('bnc'): 308, np.str_('bo'): 309, np.str_('board'): 310, np.str_('boat'): 311, np.str_('body'): 312, np.str_('bodycon'): 313, np.str_('bold'): 314, np.str_('boldcolored'): 315, np.str_('bolly'): 316, np.str_('bolster'): 317, np.str_('bombarded'): 318, np.str_('bonsai'): 319, np.str_('bonzer'): 320, np.str_('booking'): 321, np.str_('bookmark'): 322, np.str_('boot'): 323, np.str_('bootie'): 324, np.str_('boots'): 325, np.str_('boots\nboots'): 326, np.str_('booty'): 327, np.str_('border'): 328, np.str_('borne'): 329, np.str_('bostan'): 330, np.str_('both'): 331, np.str_('bottle'): 332, np.str_('bottom'): 333, np.str_('bottom\ngreen'): 334, np.str_('bounce'): 335, np.str_('bound'): 336, np.str_('bow'): 337, np.str_('box'): 338, np.str_('boxezyprnt'): 339, np.str_('boxnote'): 340, np.str_('boy'): 341, np.str_('boys'): 342, np.str_('bracelet'): 343, np.str_('braceletstyle'): 344, np.str_('brand'): 345, np.str_('branded'): 346, np.str_('brandedacm'): 347, np.str_('branding'): 348, np.str_('brandsisel'): 349, np.str_('brass'): 350, np.str_('break'): 351, np.str_('breath'): 352, np.str_('breathability'): 353, np.str_('breathable'): 354, np.str_('bred'): 355, np.str_('breitling'): 356, np.str_('bright'): 357, np.str_('brighten'): 358, np.str_('brighter'): 359, np.str_('brilliantly'): 360, np.str_('bring'): 361, np.str_('brings'): 362, np.str_('bristled'): 363, np.str_('britex'): 364, np.str_('briza'): 365, np.str_('brn'): 366, np.str_('broad'): 367, np.str_('broken'): 368, np.str_('brooch'): 369, np.str_('brown'): 370, np.str_('brownblack'): 371, np.str_('bruno'): 372, np.str_('brush'): 373, np.str_('brushed'): 374, np.str_('bruview'): 375, np.str_('bt'): 376, np.str_('btbt'): 377, np.str_('bubble'): 378, np.str_('buckle'): 379, np.str_('buckleligans'): 380, np.str_('buddha'): 381, np.str_('budding'): 382, np.str_('budh\npearl'): 383, np.str_('buildtrack'): 384, np.str_('buildtracks'): 385, np.str_('built'): 386, np.str_('bulaky'): 387, np.str_('bump'): 388, np.str_('bus'): 389, np.str_('business'): 390, np.str_('businessspecifications'): 391, np.str_('bust'): 392, np.str_('bustling'): 393, np.str_('but'): 394, np.str_('butterfly'): 395, np.str_('button'): 396, np.str_('button\nblack'): 397, np.str_('button\nblue'): 398, np.str_('buttoned'): 399, np.str_('buy'): 400, np.str_('buying'): 401, np.str_('by'): 402, np.str_('c'): 403, np.str_('cable'): 404, np.str_('cabling'): 405, np.str_('calculation'): 406, np.str_('calibre'): 407, np.str_('calibro'): 408, np.str_('called'): 409, np.str_('calnedars'): 410, np.str_('camera'): 411, np.str_('camerii'): 412, np.str_('can'): 413, np.str_('cancellation'): 414, np.str_('candied'): 415, np.str_('candy'): 416, np.str_('cannelita'): 417, np.str_('cant'): 418, np.str_('canvas'): 419, np.str_('cap'): 420, np.str_('capacity'): 421, np.str_('cape'): 422, np.str_('capsule'): 423, np.str_('car'): 424, np.str_('carat'): 425, np.str_('caratlane'): 426, np.str_('carbohydrate'): 427, np.str_('card'): 428, np.str_('card\nnishtaa'): 429, np.str_('cardigan'): 430, np.str_('care'): 431, np.str_('carefully'): 432, np.str_('caressing'): 433, np.str_('cargo'): 434, np.str_('carl'): 435, np.str_('carlcheetah'): 436, np.str_('carlton'): 437, np.str_('caron'): 438, np.str_('carpentry'): 439, np.str_('carrel'): 440, np.str_('carry'): 441, np.str_('cartier'): 442, np.str_('case'): 443, np.str_('casedeal'): 444, np.str_('casela'): 445, np.str_('cash'): 446, np.str_('cashmilon'): 447, np.str_('casing'): 448, np.str_('casual'): 449, np.str_('casual\nsize'): 450, np.str_('casuals'): 451, np.str_('casualsaw'): 452, np.str_('casw'): 453, np.str_('cat'): 454, np.str_('catbird'): 455, np.str_('catch'): 456, np.str_('category'): 457, np.str_('cathedral'): 458, np.str_('catwalk'): 459, np.str_('cauba'): 460, np.str_('cause'): 461, np.str_('caused'): 462, np.str_('cctv'): 463, np.str_('ceiling'): 464, np.str_('celebra'): 465, np.str_('celebrate'): 466, np.str_('cellbazaar'): 467, np.str_('central'): 468, np.str_('centre'): 469, np.str_('certification'): 470, np.str_('certified'): 471, np.str_('cf'): 472, np.str_('cgr'): 473, np.str_('chain'): 474, np.str_('chainlike'): 475, np.str_('chanderi'): 476, np.str_('chandra\nhessonite'): 477, np.str_('change'): 478, np.str_('chaniya'): 479, np.str_('channel'): 480, np.str_('character'): 481, np.str_('charge'): 482, np.str_('charm'): 483, np.str_('charming'): 484, np.str_('cheater'): 485, np.str_('check'): 486, np.str_('checked'): 487, np.str_('checkered'): 488, np.str_('cheetablue'): 489, np.str_('chest'): 490, np.str_('chestin'): 491, np.str_('chic'): 492, np.str_('chill'): 493, np.str_('chilled'): 494, np.str_('chime'): 495, np.str_('chinese'): 496, np.str_('chino'): 497, np.str_('chloride'): 498, np.str_('chlorine'): 499, np.str_('choice'): 500, np.str_('choli'): 501, np.str_('choose'): 502, np.str_('christmas'): 503, np.str_('chrome'): 504, np.str_('chrono'): 505, np.str_('chronograph'): 506, np.str_('chronomat'): 507, np.str_('chunky'): 508, np.str_('circuit'): 509, np.str_('city'): 510, np.str_('civil'): 511, np.str_('ck'): 512, np.str_('clack'): 513, np.str_('clara'): 514, np.str_('clarity'): 515, np.str_('clarityvssi'): 516, np.str_('clariz'): 517, np.str_('clasp'): 518, np.str_('class'): 519, np.str_('classic'): 520, np.str_('classy'): 521, np.str_('clean'): 522, np.str_('cleaned'): 523, np.str_('cleaner'): 524, np.str_('cleaning'): 525, np.str_('clear'): 526, np.str_('click'): 527, np.str_('clincher'): 528, np.str_('cll'): 529, np.str_('clock'): 530, np.str_('clog'): 531, np.str_('close'): 532, np.str_('closed'): 533, np.str_('closerspecifications'): 534, np.str_('closure'): 535, np.str_('cloth'): 536, np.str_('clothes'): 537, np.str_('clothing'): 538, np.str_('cloths\xa0use'): 539, np.str_('cloudy'): 540, np.str_('clove'): 541, np.str_('club'): 542, np.str_('clubbed'): 543, np.str_('clubbing'): 544, np.str_('clutch'): 545, np.str_('clutching'): 546, np.str_('cm'): 547, np.str_('cmbengal'): 548, np.str_('cmfirst'): 549, np.str_('cmom'): 550, np.str_('cmsantosh'): 551, np.str_('cmspecifications'): 552, np.str_('cmsspecifications'): 553, np.str_('coa'): 554, np.str_('coaxial'): 555, np.str_('cobra'): 556, np.str_('cocktail'): 557, np.str_('code'): 558, np.str_('coffee'): 559, np.str_('coin'): 560, np.str_('colat'): 561, np.str_('colatm'): 562, np.str_('colatmw'): 563, np.str_('colbrii'): 564, np.str_('cold'): 565, np.str_('collage'): 566, np.str_('collar'): 567, np.str_('collection'): 568, np.str_('color'): 569, np.str_('colored'): 570, np.str_('colorful'): 571, np.str_('colorfull'): 572, np.str_('colorjk'): 573, np.str_('colororange'): 574, np.str_('colour'): 575, np.str_('coloured'): 576, np.str_('colouredboots'): 577, np.str_('colourful'): 578, np.str_('combination'): 579, np.str_('combined'): 580, np.str_('combo'): 581, np.str_('come'): 582, np.str_('comfordry'): 583, np.str_('comfort'): 584, np.str_('comfort\ncottonpolyesterlycra\nmachine'): 585, np.str_('comfortable'): 586, np.str_('comfortasics'): 587, np.str_('comfy'): 588, np.str_('committed'): 589, np.str_('communicate'): 590, np.str_('communicating'): 591, np.str_('companion'): 592, np.str_('company'): 593, np.str_('compared'): 594, np.str_('compartment'): 595, np.str_('compass'): 596, np.str_('compatible'): 597, np.str_('competition'): 598, np.str_('complemantry'): 599, np.str_('complement'): 600, np.str_('complemented'): 601, np.str_('complete'): 602, np.str_('completely'): 603, np.str_('completes'): 604, np.str_('compliment'): 605, np.str_('complimenting'): 606, np.str_('componentry'): 607, np.str_('composition'): 608, np.str_('concerned'): 609, np.str_('condition'): 610, np.str_('conditioner'): 611, np.str_('conditioning'): 612, np.str_('conditoner'): 613, np.str_('conductor'): 614, np.str_('confidence'): 615, np.str_('connect'): 616, np.str_('connection'): 617, np.str_('connectionthey'): 618, np.str_('connector'): 619, np.str_('connectorsuperior'): 620, np.str_('connoisseur'): 621, np.str_('conscious'): 622, np.str_('considered'): 623, np.str_('consists'): 624, np.str_('construction'): 625, np.str_('consumedbuildtrack'): 626, np.str_('consumer'): 627, np.str_('consumption'): 628, np.str_('contact'): 629, np.str_('container'): 630, np.str_('contains'): 631, np.str_('contemporary'): 632, np.str_('content'): 633, np.str_('contour'): 634, np.str_('contrast'): 635, np.str_('contrasting'): 636, np.str_('contribution'): 637, np.str_('control'): 638, np.str_('controller'): 639, np.str_('convenience'): 640, np.str_('converting'): 641, np.str_('cool'): 642, np.str_('cooler'): 643, np.str_('coordinate'): 644, np.str_('copper'): 645, np.str_('copyright'): 646, np.str_('coral'): 647, np.str_('corner'): 648, np.str_('corporate'): 649, np.str_('corrosion'): 650, np.str_('cost'): 651, np.str_('cost\nring'): 652, np.str_('costa'): 653, np.str_('costume'): 654, np.str_('cotton'): 655, np.str_('cottoneccellente'): 656, np.str_('cottonjaipur'): 657, np.str_('cottonthis'): 658, np.str_('count'): 659, np.str_('countdown'): 660, np.str_('counter'): 661, np.str_('country'): 662, np.str_('couple'): 663, np.str_('courier'): 664, np.str_('cover'): 665, np.str_('covered'): 666, np.str_('coverspecifications'): 667, np.str_('cow'): 668, np.str_('cowboy'): 669, np.str_('cozy'): 670, np.str_('cpp'): 671, np.str_('crafted'): 672, np.str_('cranberry'): 673, np.str_('crazy'): 674, np.str_('cream'): 675, np.str_('create'): 676, np.str_('creates'): 677, np.str_('creating'): 678, np.str_('creation'): 679, np.str_('credo'): 680, np.str_('crew'): 681, np.str_('cricket'): 682, np.str_('cricketer'): 683, np.str_('cricketturbo'): 684, np.str_('crochet'): 685, np.str_('crocs'): 686, np.str_('crop'): 687, np.str_('cross'): 688, np.str_('crotch'): 689, np.str_('crowd'): 690, np.str_('crystal'): 691, np.str_('crystaleternal'): 692, np.str_('ct'): 693, np.str_('cubbling'): 694, np.str_('cubic'): 695, np.str_('cuff'): 696, np.str_('cuffs\npullon'): 697, np.str_('culture'): 698, np.str_('cultured'): 699, np.str_('cup'): 700, np.str_('curation'): 701, np.str_('curblue'): 702, np.str_('current'): 703, np.str_('curtain'): 704, np.str_('curtainelegance'): 705, np.str_('curve'): 706, np.str_('curved'): 707, np.str_('cushion'): 708, np.str_('cushioned'): 709, np.str_('cushioning'): 710, np.str_('custom'): 711, np.str_('customer'): 712, np.str_('customized'): 713, np.str_('cut'): 714, np.str_('cute'): 715, np.str_('cutout'): 716, np.str_('cv'): 717, np.str_('cycle'): 718, np.str_('cycling'): 719, np.str_('d'): 720, np.str_('daathu'): 721, np.str_('daily'): 722, np.str_('dainty'): 723, np.str_('damage'): 724, np.str_('damaged'): 725, np.str_('damp'): 726, np.str_('dark'): 727, np.str_('darkblue'): 728, np.str_('darker'): 729, np.str_('dash'): 730, np.str_('date'): 731, np.str_('daughter'): 732, np.str_('day'): 733, np.str_('day\nlive'): 734, np.str_('dayspecifications'): 735, np.str_('daytoday'): 736, np.str_('dazzle'): 737, np.str_('dcompass'): 738, np.str_('dcor'): 739, np.str_('dcosmart'): 740, np.str_('deal'): 741, np.str_('dear'): 742, np.str_('dearfoams'): 743, np.str_('decor'): 744, np.str_('decouples'): 745, np.str_('deep'): 746, np.str_('defect'): 747, np.str_('defined'): 748, np.str_('definite'): 749, np.str_('definitely'): 750, np.str_('definition'): 751, np.str_('definition\nviscose'): 752, np.str_('degree'): 753, np.str_('degreeposition'): 754, np.str_('deisgn'): 755, np.str_('delay'): 756, np.str_('delectable'): 757, np.str_('deliver'): 758, np.str_('delivering'): 759, np.str_('delivery'): 760, np.str_('demo'): 761, np.str_('denim'): 762, np.str_('denny'): 763, np.str_('deodorize'): 764, np.str_('depending'): 765, np.str_('depth'): 766, np.str_('described'): 767, np.str_('description'): 768, np.str_('deserve'): 769, np.str_('desiger'): 770, np.str_('design'): 771, np.str_('design\nboots'): 772, np.str_('design\ndiamond'): 773, np.str_('designed'): 774, np.str_('designer'): 775, np.str_('designjqr'): 776, np.str_('designspecifications'): 777, np.str_('desired'): 778, np.str_('desk'): 779, np.str_('despecifications'): 780, np.str_('detachable'): 781, np.str_('detail'): 782, np.str_('detailing'): 783, np.str_('detection'): 784, np.str_('detector'): 785, np.str_('detergent'): 786, np.str_('device'): 787, np.str_('dgblackgold'): 788, np.str_('dgred'): 789, np.str_('dhaatu'): 790, np.str_('dhaatu\nregarding'): 791, np.str_('dhaatus'): 792, np.str_('diagonally'): 793, np.str_('dial'): 794, np.str_('diameter'): 795, np.str_('diamond'): 796

In [73]:
df

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,"[key, feature, of, alisha, solid, womens, cycl...",No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,"[fabhomedecor, fabric, double, sofa, bed, fini...",No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,"[key, feature, of, aw, belly, sandal, wedge, h...",No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,"[key, feature, of, alisha, solid, womens, cycl...",No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,"[specification, of, sicons, all, purpose, arni...",No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,a48082f2eb2ae7b9e1f91303f167fb81,2016-01-06 18:20:45 +0000,http://www.flipkart.com/karatcraft-wadell-gold...,Karatcraft Wadell Gold Diamond 18 K Ring,"[""Jewellery >> Rings""]",RNGE88Q9NXGU2ZYW,44226.0,30741.0,"[""http://img5a.flixcart.com/image/ring/9/f/n/r...",False,"[karatcraft, wadell, gold, diamond, , k, ring,...",No rating available,No rating available,Karatcraft,"{""product_specification""=>[{""key""=>""Pack of"", ..."
496,fbf96347f0c35de034e8c2b9c6b5740c,2016-01-06 18:20:45 +0000,http://www.flipkart.com/yna-aviator-sunglasses...,YNA Aviator Sunglasses,"[""Sunglasses""]",SGLE7ZK8SAHENQNJ,1199.0,299.0,"[""http://img6a.flixcart.com/image/sunglass/q/n...",False,"[yna, aviator, sunglass, , buy, yna, aviator, ...",No rating available,No rating available,NaN,"{""product_specification""=>[{""key""=>""Case"", ""va..."
497,4a9bbd6df73c3d2da798aaeb314ffa27,2016-01-06 18:20:45 +0000,http://www.flipkart.com/ditu-kritu-warrior-avi...,Ditu&Kritu Warrior Aviator Sunglasses,"[""Sunglasses""]",SGLEABFPHFPFTNBE,999.0,399.0,"[""http://img5a.flixcart.com/image/sunglass/n/b...",False,"[ditukritu, warrior, aviator, sunglass, , buy,...",4.7,4.7,NaN,"{""product_specification""=>[{""key""=>""Size"", ""va..."
498,9d87bafdcf94cdef4456fae11542fc7d,2016-01-06 18:20:45 +0000,http://www.flipkart.com/american-crew-solid-wo...,American Crew Solid Women's Track Pants,"[""Clothing >> Women's Clothing >> Sports & Gym...",TKPECMHB4F3FGXHZ,799.0,760.0,"[""http://img6a.flixcart.com/image/track-pant/b...",False,"[american, crew, solid, womens, track, pants, ...",No rating available,No rating available,NaN,"{""product_specification""=>[{""key""=>""Ideal For""..."
499,51859c73c20ed8abf623483c14ec7764,2016-01-06 18:20:45 +0000,http://www.flipkart.com/allen-solly-girl-s-gat...,Allen Solly Girl's Gathered Dress,"[""Clothing >> Kids' Clothing >> Girls Wear >> ...",DREECZJEGFFEWCW4,1599.0,1119.0,"[""http://img6a.flixcart.com/image/dress/b/h/d/...",False,"[allen, solly, girl, gathered, dress, , buy, b...",No rating available,No rating available,NaN,"{""product_specification""=>[{""key""=>""Ideal For""..."

In [74]:
res = np.zeros(len(bow))
res

array([0., 0., 0., ..., 0., 0., 0.], shape=(3086,))

In [75]:
i = df.description[:1]
values, counts = np.unique_counts(i[0])
print(values, counts)

res = np.zeros(len(bow))

for i in range(len(counts)):
    res[bow.get(values[i])] = counts[i]
    
print(res)

['' 'additional' 'alisha' 'althtp' 'bleach' 'box' 'care' 'code' 'content'
 'cotton' 'cycling' 'detail' 'do' 'fabric' 'feature' 'for' 'general'
 'gentle' 'ideal' 'in' 'key' 'lukewarm' 'lycra' 'machine' 'navy'
 'navyspecifications' 'not' 'number' 'of' 'pack' 'package' 'pattern' 'red'
 'sale' 'short' 'solid' 'style' 'the' 'type' 'wash' 'water' 'womens'] [2 1 2 1 1 1 1 1 1 2 3 3 1 2 1 1 1 1 1 3 1 1 2 1 1 1 1 1 4 1 1 1 1 1 5 3 1
 1 1 1 1 3]
[2. 0. 0. ... 0. 0. 0.]

In [76]:
# buf = df['description'].apply(tokenize)

# df['tokenized'] = buf
# df.head(5)

In [77]:
def tokenize(x):
    global bow
    res = np.zeros(len(bow))
    values, counts = np.unique_counts(x)
    for i in range(len(counts)):
        res[bow.get(values[i])] = counts[i]
    return res 

buf = df['description'].apply(tokenize)

df['tokenized'] = buf
df.head(5)

  
    
df.loc[:,'tokenized'] = df['description'].apply(tokenize)
df

C:\Users\topi7\AppData\Local\Temp\ipykernel_35016\2824746538.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tokenized'] = buf

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications,tokenized
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,"[key, feature, of, alisha, solid, womens, cycl...",No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ...","[2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,"[fabhomedecor, fabric, double, sofa, bed, fini...",No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati...","[33.0, 17.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,"[key, feature, of, aw, belly, sandal, wedge, h...",No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""...","[4.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,"[key, feature, of, alisha, solid, womens, cycl...",No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ...","[2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,"[specification, of, sicons, all, purpose, arni...",No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",...","[2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,a48082f2eb2ae7b9e1f91303f167fb81,2016-01-06 18:20:45 +0000,http://www.flipkart.com/karatcraft-wadell-gold...,Karatcraft Wadell Gold Diamond 18 K Ring,"[""Jewellery >> Rings""]",RNGE88Q9NXGU2ZYW,44226.0,30741.0,"[""http://img5a.flixcart.com/image/ring/9/f/n/r...",False,"[karatcraft, wadell, gold, diamond, , k, ring,...",No rating available,No rating available,Karatcraft,"{""product_specification""=>[{""key""=>""Pack of"", ...","[25.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
496,fbf96347f0c35de034e8c2b9c6b5740c,2016-01-06 18:20:45 +0000,http://www.flipkart.com/yna-aviator-sunglasses...,YNA Aviator Sunglasses,"[""Sunglasses""]",SGLE7ZK8SAHENQNJ,1199.0,299.0,"[""http://img6a.flixcart.com/image/sunglass/q/n...",False,"[yna, aviator, sunglass, , buy, yna, aviator, ...",No rating available,No rating available,NaN,"{""product_specification""=>[{""key""=>""Case"", ""va...","[2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
497,4a9bbd6df73c3d2da798aaeb314ffa27,2016-01-06 18:20:45 +0000,http://www.flipkart.com/ditu-kritu-warrior-avi...,Ditu&Kritu Warrior Aviator Sunglasses,"[""Sunglasses""]",SGLEABFPHFPFTNBE,999.0,399.0,"[""http://img5a.flixcart.com/image/sunglass/n/b...",False,"[ditukritu, warrior, aviator, sunglass, , buy,...",4.7,4.7,NaN,"{""product_specification""=>[{""key""=>""Size"", ""va...","[2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
498,9d87bafdcf94cdef4456fae11542fc7d,2016-01-06 18:20:45 +0000,http://www.flipkart.com/american-crew-solid-wo...,American Crew Solid Women's Track Pants,"[""Clothing >> Women's Clothing >> Sports & Gym...",TKPECMHB4F3FGXHZ,799.0,760.0,"[""http://img6a.flixcart.com/image/track-pant/b...",False,"[american, crew, solid, womens, track, pants, ...",No rating available,No rating available,NaN,"{""product_specification""=>[{""key""=>""Ideal For""...","[26.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
499,51859c73c20ed8abf623483c14ec7764,2016-01-06 18:20:45 +0000,http://www.flipkart.com/allen-solly-girl-s-gat...,Allen Solly Girl's Gathered Dress,"[""Clothing >> Kids' Clothing >> Girls Wear >> ...",DREECZJEGFFEWCW4,1599.0,1119.0,"[""http://img6a.flixcart.com/image/dress/b/h/d/...",False,"[allen, solly, girl, gathered, dress, , buy, b...",No rating available,No rating available,NaN,"{""product_specification""=>[{""key""=>""Ideal For""...","[2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [78]:
#np.sort(np.array(list(zip(values, counts))), axis = 0)

In [79]:
bow = dict(zip(values, counts))

In [80]:
bow

{np.str_(''): np.int64(2),
 np.str_('additional'): np.int64(1),
 np.str_('alisha'): np.int64(2),
 np.str_('althtp'): np.int64(1),
 np.str_('bleach'): np.int64(1),
 np.str_('box'): np.int64(1),
 np.str_('care'): np.int64(1),
 np.str_('code'): np.int64(1),
 np.str_('content'): np.int64(1),
 np.str_('cotton'): np.int64(2),
 np.str_('cycling'): np.int64(3),
 np.str_('detail'): np.int64(3),
 np.str_('do'): np.int64(1),
 np.str_('fabric'): np.int64(2),
 np.str_('feature'): np.int64(1),
 np.str_('for'): np.int64(1),
 np.str_('general'): np.int64(1),
 np.str_('gentle'): np.int64(1),
 np.str_('ideal'): np.int64(1),
 np.str_('in'): np.int64(3),
 np.str_('key'): np.int64(1),
 np.str_('lukewarm'): np.int64(1),
 np.str_('lycra'): np.int64(2),
 np.str_('machine'): np.int64(1),
 np.str_('navy'): np.int64(1),
 np.str_('navyspecifications'): np.int64(1),
 np.str_('not'): np.int64(1),
 np.str_('number'): np.int64(1),
 np.str_('of'): np.int64(4),
 np.str_('pack'): np.int64(1),
 np.str_('package'): np.int64(1),
 np.str_('pattern'): np.int64(1),
 np.str_('red'): np.int64(1),
 np.str_('sale'): np.int64(1),
 np.str_('short'): np.int64(5),
 np.str_('solid'): np.int64(3),
 np.str_('style'): np.int64(1),
 np.str_('the'): np.int64(1),
 np.str_('type'): np.int64(1),
 np.str_('wash'): np.int64(1),
 np.str_('water'): np.int64(1),
 np.str_('womens'): np.int64(3)}

# word2vec

In [81]:
from gensim.models import Word2Vec
import gensim
from nltk.tokenize import sent_tokenize, word_tokenize
nltk.download('punkt_tab')
import warnings

warnings.filterwarnings(action='ignore')

ImportError: cannot import name 'triu' from 'scipy.linalg.special_matrices' (C:\Users\topi7\OneDrive\Desktop\FEFU\.venv\Lib\site-packages\scipy\linalg\special_matrices.py)

In [ ]:
model1 = gensim.models.Word2Vec(df['description'], min_count=1,
                                vector_size=100, window=5)
df

# Тут неработат кому нада дописат

In [147]:
model1.wv.similarity(df['description'][0], df['description'][1])

ValueError: shapes (64,100) and (752,100) not aligned: 100 (dim 1) != 752 (dim 0)